mysql:
  host: 'mysql.fuck'
  port: 3306
  username: 'epic-fucking-username'
  password: 'IwAtChPoRn69'
discord:
  application-id: 574027384983126026
  bot-token: abcd1234
  # This will also be used to get the guild
  verification-channel-id: 574444791341776896
  debug: false
minecraft:
  purchases:
    # Time in seconds to ask Discord if people made purchases
    check-rate: 5
    # You can copy and paste these for multiple SKUs (yes, this is a SKU ID)
    # In commands, you can use {uuid} for the player UUID and {player} for their username
    '574028480740851713':
      commands:
      - give {uuid} apple 12
      - give {uuid} stone 5
      - 'say {name} is fucking awesome brodie!'
      # These are role IDs right here
      apply-roles:
      - 530973480322334741
      remove-roles:
      - 571535325193830441
    '36592368576236593':
      commands:
      - give {uuid} stick 16
      - give {uuid} diamond 22
      - 'say {name} is fucking lit brodie!'
      # These are role IDs right here
      apply-roles:
      - 530973480322334741
      remove-roles: []
messages:
  # In these messages, you can use {code} for their verification code and {channel} for the name of the verification channel
  minecraft:
    purchase-successful: '&aYou have successfully claimed all your purchases!'
    no-purchases: '&eThere are no pending purchases to confirm!'
    account-not-linked: '&cYou need to have a linked account to continue!'
    unlink-success: '&aYour account has been successfully unlinked!'
    account-already-linked: '&eYour Discord account is already linked!'
    verify-pending: '&cYour verification is still pending. Your code is &e{code}'
    begin-verify: '&aPlease type &e{code}&a in #{channel} to connect your account.'
    begin-reload: '&eReloading the plugin'
    finish-reload: '&aPlugin successfully reloaded'
  discord:
    verify-description: '**Successfully linked your Minecraft account**'
    color: '#33c63b'