mysql:
  host: 'mysql.fuck'
  port: 3306
  username: 'epic-fucking-username'
  password: 'IwAtChPoRn69'
discord:
  application-id: 574027384983126026
  bot-token: abcd1234
  verification-channel-id: 574444791341776896
  debug: false
minecraft:
  purchases:
    check-rate: 5
    '574028480740851713':
      commands:
      - give {uuid} apple 12
      - give {uuid} stone 5
      - 'say {name} is fucking awesome brodie!'
      apply-roles:
      - 530973480322334741
      remove-roles:
      - 571535325193830441
messages:
  minecraft:
    purchase-successful: '&aYou have successfully claimed all your purchases!'
    no-purchases: '&eThere are no pending purchases to confirm!'
    account-not-linked: '&cYou need to have a linked account to continue!'
    account-already-linked: '&eYour Discord account is already linked!'
    verify-pending: '&cYour verification is still pending. Your code is &e{code}'
    begin-verify: '&aPlease type &e{code}&a in #{channel} to connect your account.'
    begin-reload: '&eReloading the plugin'
    finish-reload: '&aPlugin successfully reloaded'
  discord:
    verify-description: '**Successfully linked your Minecraft account**'
    color: '#33c63b'